### ISSUE TITLE
Schématiser le réseau de l'entreprise dans son état actuel (avant notre proposition d'évolution).

### ISSUE THREAD

**Issue by 101-b** [arthurruby/cyber-cogip#14]
---

#### Infrastructure

**Comment by arthurruby** [comment]
### Réseau actuel de l'entreprise:

- Des postes de travail fixes sur Win10 pas séparés par services
- Un vieux serveur Ubuntu
- Zéro pare-feu
- Pas bien

![COGIP-Page-1](https://user-images.githubusercontent.com/83712022/118774309-fa093280-b885-11eb-87ca-f57c9b7c3aca.png)
