### ISSUE TITLE
Créer le MCD

### ISSUE THREAD

**Issue by 101-b** [arthurruby/cyber-cogip#19]
---

- Avec ou sans portefeuille client (entre order et user) ? --> SANS
- classe Enum pour les rôles admin, basic, ... (pas d'entrée bdd donc) --> NON
- classe User côté app
- ...

**Comment by arthurruby** [comment]
Premier MCD possible: avec deux adresses et une table TVA.

Ca me paraît un peu compliqué l'histoire de la TVA, et de la difficulté un peu pour rien dans la mesure où on ne vendra pas de produits qui ont des taux réduits (presse, livres, animaux vivants destinés à la boucherie...). Je pense qu'on peut donc juste se contenter d'appliquer un taux de TVA unique. Le prix réel serait donc un champ calculé. 

Il faudrait peut-être aussi faire un prix calculé pour les frais de livraison en plus.

![cyber_cogip_mcd_1](https://user-images.githubusercontent.com/83712022/117886649-d35c6200-b2af-11eb-8874-60e19357d1c4.png)

**Comment by 101-b** [comment]
Price en int plutôt qu'en float, et on travaille en centimes ?

**Comment by 101-b** [comment]
Sinon pour la TVA : un tableau, juste une entrée TVA20, et hop ? Après si besoin de taux différents, suffira de créer des TVA8, TVADOMTOM, etc. dans le tableau et de les appeler au besoin pour calculer d'autres valeurs ? Qu'elle soit en tableau ou en constante ne change pas gd chose finalement. On peut la lier à Order sur le mcd : les taux seront utilisés pour calculer une valeur là bas. J'ai bien compris ?

**Comment by arthurruby** [comment]
> 
> 
> Price en int plutôt qu'en float, et on travaille en centimes ?

D'après les infos que j'ai trouvées sur les intewebs il est préconisé d'utiliser le type DECIMAL pour tout ce qui est manipulation de chiffres à virgule (et surtout de pognon) en SQL, qui a un comportement le plus proche de ce que nous êtres humains attendons d'un nombre à virgule. 



> 
> 
> Sinon pour la TVA : un tableau, juste une entrée TVA20, et hop ? Après si besoin de taux différents, suffira de créer des TVA8, TVADOMTOM, etc. dans le tableau et de les appeler au besoin pour calculer d'autres valeurs ? Qu'elle soit en tableau ou en constante ne change pas gd chose finalement. 

Après avoir fait du JPA et des relations (j'étais un peu en retard là-dessus), mon avis a un peu évolué sur la question. Je trouvais que c'était un peu trop de complexité inutile de rajouter une table TVA pour si peu, mais en fait c'est tellement facile à gérer côté applicatif qu'on s'en fout. Donc on peut garder une table TVA à côté et lui mettre les principaux taux en vigueur en France Métropolitaine et voilà. 



>
>
>On peut la lier à Order sur le mcd : les taux seront utilisés pour calculer une valeur là bas. J'ai bien compris ?

La TVA reste quand même lié au produit, pas à la commande (la taxe s'applique sur chaque produit). Donc le lien reste là et pas avec "Order". Après, pour la sélection du taux approprié, dans le cas d'une prise en charge desdits taux particuliers (DOM, Corse, etc.) l'employé pourrait le faire manuellement, ou on pourrait faire un traitement automatisé qui vérifie l'attribut si customer.zipCode commence par "974" alors ajuste le taux de TVA, par exemple. Mais ça serait pour plus tard 😉 .

**Comment by 101-b** [comment]
Agree ! Rémi a posé la question à Sega qui avait l'air d'être ok pour utiliser du Double. Je ne sais pas si cela change grand chose au final entre le float et le double à part le nombre de chiffres, un peu comme int short et long. En tous cas, on n'utilisera pas de int pour les prix. J'avais vu ça dans un tuto d'e-shop en PHP, le gars disait de faire comme ça... je sais pas pourquoi finalement.

**Comment by arthurruby** [comment]
Du coup je propose ce MCD (j'ai juste changé un champs dans les adresses pour qu'on puisse mettre un complément d'adresse):

![cyber_cogip_mcd_3](https://user-images.githubusercontent.com/83712022/118355592-0e40ed00-b571-11eb-911f-aac2710e5f2f.png)

**Comment by arthurruby** [comment]
Du coup si ça vous convient dites-le et on peut clôturer, et si ça vous convient pas dites-nous ce que vous voudriez changer.

**Comment by sandrine-gatari** [comment]
c'est ok pour,moi il y a tout les points d'amélioration qu'on a discuté dèrnierement @arthurruby

**Comment by 101-b** [comment]
Prend-on en charge m'état du produit ?
_Rajouter un champ "état du produit" d'un caractère (disponible, rupture de stock fournisseur, etc.)_
Ca signifierait ajouter une table "product statement" et un champs dans Product.

**Comment by arthurruby** [comment]
C'est l'attribut "Status" (dans Order aussi). Après c'est toujours la même question de savoir si c'est judicieux de passer par l'un ou l'autre:

Une enum dans le code:
- plus léger pour l'accès 
- mais nécessite un accès au code source et recompiler l'appli pour modifier les valeurs
- adapté pour des choses qui ne devraient être modifiées qu'exceptionnellement

Ou bien une table de BDD
- un peu plus lourd
- mais facile de modifier les valeurs par un simple utilisateur admin
- adapté pour des choses qui risquent d'être modifiées plus régulièrement

Les deux choix sont possibles et défendables. 

[(Un peu d'infos dessus)](https://stackoverflow.com/questions/24680744/when-to-use-an-enum-or-a-small-table-in-a-relational-database)

**Comment by arthurruby** [comment]
Suite à l'entretien avec Séga, les modifications discutées et apportées au diagramme de classe, je poste ici une version mise à jour et clos l'issue.

![cyber_cogip_mcd_4](https://user-images.githubusercontent.com/83712022/118874869-ab8e7f00-b8eb-11eb-959c-fb0045226201.png)
