### ISSUE TITLE
Créer le MLD

### ISSUE THREAD

**Issue by 101-b** [arthurruby/cyber-cogip#20]
---

**Comment by arthurruby** [comment]
### Propositions de MLDs en lien avec les MCDs proposés dans l'issue #19 

La version "lourde":

![cyber_cogip_mld_1](https://user-images.githubusercontent.com/83712022/117887298-c55b1100-b2b0-11eb-8c67-c9f780474c1c.png)

**Comment by arthurruby** [comment]
La version moins lourde:


![cyber_cogip_mld_2](https://user-images.githubusercontent.com/83712022/117887323-d015a600-b2b0-11eb-8567-7ee1b40a495f.png)

**Comment by arthurruby** [comment]
### Autre diagramme de BDD possible, version plus légère:

![cyber_cogip_db_2](https://user-images.githubusercontent.com/83712022/117887788-85e0f480-b2b1-11eb-9ce7-0ff97ffe554b.png)

**Comment by arthurruby** [comment]
MLD mis à jour :

![cyber_cogip_mld_3](https://user-images.githubusercontent.com/83712022/118355648-595b0000-b571-11eb-97eb-03e20f13d4fd.png)

**Comment by arthurruby** [comment]
Diagramme de BDD qui va avec le MLD précédent:


![cyber_cogip_db_3](https://user-images.githubusercontent.com/83712022/118356428-7abdeb00-b575-11eb-969f-8ec115601cc9.png)

**Comment by arthurruby** [comment]
Suite à la discussion avec Séga et les modifications apportées au diagramme de classe, j'ai mis à jour le MLD et clos le sujet.

![cyber_cogip_mld_4](https://user-images.githubusercontent.com/83712022/118875049-e2fd2b80-b8eb-11eb-9f02-b16345ba931c.png)
