### ISSUE TITLE
UML - Créer le diagramme de classe

### ISSUE THREAD

**Issue by 101-b** [arthurruby/cyber-cogip#21]
---

**Comment by nico-save** [comment]
![diagrammeDeClasse (3)](https://user-images.githubusercontent.com/65293043/118775941-be6f6800-b887-11eb-836b-47188b6c69f9.png)

J'ai ça comme début de diagramme de classe

**Comment by arthurruby** [comment]
à demander:

- Agrégation/composition/rien entre User et Role?
- Relation bidirectionnelle ou pas entre Customer et Order? Customer.orders (Set<Order>) ?
- Table associative OrderHasProduct avec des champs price & quantity => Entité propre ou un Set?
- Associations bidirectionnelles utiles et pertinentes sur Category, Role, VAT, Status, Customer? Genre avoir des attributs category.products, role.users, etc?

**Comment by nico-save** [comment]
![diagrammeDeClasseV2](https://user-images.githubusercontent.com/65293043/118817221-47e85f80-b8b3-11eb-8e3e-3357543593de.png)

**Comment by nico-save** [comment]
![diagrammeDeClasseV3](https://user-images.githubusercontent.com/65293043/118829263-3fe1ed00-b8be-11eb-9abc-0f9521ba4b53.png)

**Comment by 101-b** [comment]
passage en <<enum>> (sans liens d'association) : OrderStatus, Role, ProductStatus

**Comment by 101-b** [comment]
*<< enum >>

**Comment by 101-b** [comment]
_Agrégation/composition/rien entre User et Role?_ => enum
_Relation bidirectionnelle ou pas entre Customer et Order? Customer.orders (Set) ?_ => oui
_Table associative OrderHasProduct avec des champs price & quantity_ => Entité propre ou un Set? => entité (extra data)
_Associations bidirectionnelles utiles et pertinentes sur Category, Role, VAT, Status, Customer? Genre avoir des attributs category.products, role.users, etc?__ => non ormis Custumer -- Order

**Comment by nico-save** [comment]
![diagrammeDeClasseV3 (1)](https://user-images.githubusercontent.com/65293043/118833283-9ef53100-b8c1-11eb-8dc7-9f185770f394.png)

**Comment by 101-b** [comment]
Est-ce que l'on valide ce diagramme de classe ?

**Comment by nico-save** [comment]
Je votes pour

**Comment by arthurruby** [comment]
> 
> 
> Est-ce que l'on valide ce diagramme de classe ?

oui!
