### ISSUE TITLE
Maquetter l'application

### ISSUE THREAD

**Issue by 101-b** [arthurruby/cyber-cogip#23]
---

**Comment by arthurruby** [comment]
Pour faire des maquettes, vous pouvez télécharger [Balsamic Wireframes ](https://balsamiq.com/wireframes/desktop/)(en version d'essai 30 jours).

Sinon, passez par le site que Pierre Jehan nous avait montré, [Diagrams.net](https://app.diagrams.net/?src=about). Et pour avoir les formes adaptées au maquettage, cliquez sur "**More Shapes**" tout en bas à gauche, puis dans la catégorie "**Software**" sélectionnez "**Mockups**" dans la liste. 
 
 A noter que je n'ai jamais  utilisé Diagrams.net pour faire des maquettes. Je pense que Balsamic est beaucoup plus complet, mais plus contraignant.
