### ISSUE TITLE
Créer le Model de base

### ISSUE THREAD

**Issue by 101-b** [arthurruby/cyber-cogip#29]
#### Créer les templates généraux du site internet:

- header
- footer
- master

#### Doc:

https://www.thymeleaf.org/doc/articles/layouts.html

#### Notes: 

J'inclue Bootstrap au projet. Je le configure en full CDN.

**Comment by 101-b** [comment]
![image](https://user-images.githubusercontent.com/62948649/119387959-f59baa00-bcc9-11eb-912b-8cd371e37f53.png)

**Comment by 101-b** [comment]
![image](https://user-images.githubusercontent.com/62948649/119387993-02200280-bcca-11eb-885b-b97a062d1e56.png)

dans index.html : 
![image](https://user-images.githubusercontent.com/62948649/119388048-1401a580-bcca-11eb-851d-5360456eecd0.png)

**Comment by 101-b** [comment]
J'ai fais un layout pour donner une base graphique à l'interface. C'est en fait un header avec menu et un footer.
![image](https://user-images.githubusercontent.com/62948649/119389388-d867db00-bccb-11eb-80bc-2ce5076a59ca.png)


J'ai fait un fichier index.html qui charge Bootstrap et insert dans son body la base graphique "layout". Pour créer une vue pour le moment, il faut faire l'appel de layout en lui passant un argument dans index.html (j'ai fais les commentaires en anglais ^_^) : 
![image](https://user-images.githubusercontent.com/62948649/119388628-d2bdc580-bcca-11eb-9e57-664c3f6ff6d1.png)
J'attends d'avoir pris connaissance du fonctionnement des contrôleurs, de comment ils créent les vues, pour ajuster ça.
Je vais peut-être permettre à index.html d'accepter un argument, qui sera fourni par un contrôleur et qui correspondra à une vue.

![image](https://user-images.githubusercontent.com/62948649/119389102-74451700-bccb-11eb-9eff-f55b3daef04f.png)
Ici l'organisation des templates et des "fragments" qui sont, dans Thymeleaf, des morceaux de html que l'on peut inclure dans un template. A terme il faudra par exemple un fragment "logingForm", un "ordersList", ou un "customerDisplayer", etc. Ces fragments prendront ensuite automatiquement place entre le header et le footer grace à Thymeleaf pour former des vues.


Reste à faire : 
- résoudre le fonctionnement des contrôleurs de vue et adapter le layout
- déterminer les fragments à créer et les variables qu'ils utilisent
- intégrer les vues aux contrôleurs

**Comment by arthurruby** [comment]
Cool ça fait propre.

Y'a de la doc sur l'intégration des fragments ici (mais tu l'as peut-être déjà lue): https://www.thymeleaf.org/doc/tutorials/3.0/thymeleafspring.html#rendering-template-fragments
